name: Deploy Hive Mind
run-name: ${{ github.actor }} is deploying Hive Mind API 🚀
on: [push]
jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "18"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: Bootstrap CDK
      run: |
        npm install -g aws-cdk
        yarn install
        cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_NUMBER}}/${{ secrets.AWS_REGION }}

    - name: Deploy API
      working-directory: ./apps/api
      run: cdk deploy --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}